services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-local
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Database123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-mssql.sh:/docker-entrypoint-initdb.d/init-mssql.sh
    command: /bin/bash -c "/docker-entrypoint-initdb.d/init-mssql.sh & exec /opt/mssql/bin/sqlservr"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Database123! -C -Q 'SELECT 1' || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8080
        - WDS_SOCKET_PORT=3000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:

    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=uknf;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Database123!
      - SPRING_FLYWAY_URL=jdbc:sqlserver://mssql:1433;databaseName=uknf;encrypt=true;trustServerCertificate=true
      - SPRING_FLYWAY_USER=sa
      - SPRING_FLYWAY_PASSWORD=Database123!

volumes:
  mssql_data: