services:
  backend:
    build:
      context: ../backend
    environment:
      - SPRING_PROFILES_ACTIVE=
    ports:
      - "8080:8080"
    volumes:
      - ../backend/uploads:/app/uploads

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-local
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Database123!"   # musi mieć min. 8 znaków, wielką literę, cyfrę i znak specjalny
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"   # hostPort:containerPort
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Database123! -C -Q 'SELECT 1' || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  mssql_data: