server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:h2:mem:uknf;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true
file-storage:
  upload-dir: uploads
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs
