spring.datasource.url=jdbc:sqlserver://mssql-local:1433;databaseName=uknf;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Database123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false
spring.flyway.repair-on-migrate=true

spring.autoconfigure.exclude=
